[package]
name = "sugarfunge-api"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
structopt = "0.3"
rand = "0.8.3"
hex = "0.4.3"
actix-cors = "0.6.0-beta.8"
serde = { version = "1.0", features = ["rc","derive"] }
serde_json = "1.0"
jsonrpsee-types = "0.5.1"
url = { version = "2", features = ["serde"] }
scale-info = { version = "1.0.0", default-features = false, features = [] }
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full"] }
derive_more = { version = "0.99.0", default-features = false }
actix-web = "4.0.0-beta.21" 
awc = "3.0.0-beta.10"
dotenv = "0.15.0"

[dependencies.subxt]
# path = "../subxt"
git = "https://github.com/SugarFunge/subxt.git"
rev = "c1279cfea1935eefd2451d4d5d28d62ded35604e"

[dependencies.sp-keyring]
git = "https://github.com/paritytech/substrate.git"
branch = "polkadot-v0.9.15"
package = "sp-keyring"

[dependencies.sp-core]
git = "https://github.com/paritytech/substrate.git"
branch = "polkadot-v0.9.15"
package = "sp-core"
features = ["full_crypto"]

[dependencies.actix-web-middleware-keycloak-auth]
git = "https://github.com/JonathanJFlores/actix-web-middleware-keycloak-auth.git"
branch = "master"
package = "actix-web-middleware-keycloak-auth"

[features]
default = ["std"]
std = ["codec/std", "scale-info/std"]
